[versions]
fabric-loader = "0.16.10"
fabric-api = "0.115.10+1.21.4"
minecraft = "1.21.4"

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc", name = "fabric-api", version.ref = "fabric-api" }
fabric-gradle-minecraft = { group = "net.fabricmc", name = "fabric-gradle-minecraft", version = "0.0.0" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version = "1.7.+" }
